CREATE TABLE RM558730_PAIS (ID_PAIS NUMBER PRIMARY KEY,
                        NOME_PAIS VARCHAR2(30)NOT NULL);
                        
CREATE TABLE RM558730_ESTADO (ID_ESTADO NUMBER PRIMARY KEY,
                            NOME_ESTADO VARCHAR(30) NOT NULL,
                            ID_PAIS NUMBER);

ALTER TABLE RM558730_ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY
(ID_ESTADO) REFERENCES RM558730_PAIS (ID_PAIS)